version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
    - echo Installing dependencies...
    - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Start Pre-build and end
  build:
    commands:
      - echo Running tests...
      - pytest --junitxml=reports/junit.xml --tb=short
  post_build:
    commands:
      - echo Build completed on successfully

artifacts:
  files:
    - '**/*'
  base-directory: .
reports:
  pytest_reports:
    files:
      - reports/results.xml
    discard-paths: yes